# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
executors:
  # ここに好きな名前で executor を定義できる
  default:
    working_directory: ~/workspace
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

jobs:

  # build:
  setup:
    executor:
      # name で使いたい executor を指定
      name: default

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run setup
          command: |
            . venv/bin/activate
            # python manage.py test
            python --version
            # make test

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports

  test:
    # executor:
    #   # name で使いたい executor を指定
    #   name: default

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

  # deploy:
  #     -   

workflows:
  version: 2.1
  setup_and_deploy:
    jobs:
      - setup
      - test:
          requires:  
            - setup

# https://haskell.e-bigmoon.com/posts/2018/07-21-circleci-2.html
# https://qiita.com/nikadon/items/b7aac3b2d548ebb128ab#branches
# https://circleci.com/gh/shimakaze-git